#配置开始==================
快捷工具: '290:0'
货币名称: 金币
默认货币: EconomyAPI
生成外壳: true
游戏最小人数: 2
等待时间: 20
游戏最大血量: 100
游戏血量: 100
游戏时间: 300
掉落间隔: 20
倍率加成: 1
补给倍率: 1
死亡扣除分数: 1000
死亡扣除荣耀: 100
奖励给予: true
给予倍率: 100
给予惩罚: true
游戏费用: 1000
递归深度: 50
物品防御: true